# Generated by Django 3.2.12 on 2022-03-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='include',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='incl'),
        ),
    ]
