# Generated by Django 3.2.12 on 2022-03-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugbase', '0002_sample_include'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kingdom', models.CharField(blank=True, max_length=256, null=True, verbose_name='kingdom')),
                ('phylum', models.CharField(blank=True, max_length=256, null=True, verbose_name='kingdom')),
                ('klass', models.CharField(blank=True, max_length=256, null=True, verbose_name='kingdom')),
                ('order', models.CharField(blank=True, max_length=256, null=True, verbose_name='kingdom')),
                ('family', models.CharField(blank=True, max_length=256, null=True, verbose_name='kingdom')),
                ('genus', models.CharField(blank=True, max_length=256, null=True, verbose_name='kingdom')),
                ('counts', models.IntegerField(blank=True, null=True)),
                ('rel_freq', models.FloatField(blank=True, null=True)),
                ('sample_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugbase.sample')),
            ],
        ),
    ]
