# Generated by Django 3.2.12 on 2022-03-24 20:46

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('bugbase', '0004_rename_sample_id_sample_data_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='To_Do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=256, null=True, verbose_name='Task')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Added')),
                ('notes', markdownx.models.MarkdownxField(blank=True, verbose_name='Notes')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
            ],
            options={
                'verbose_name_plural': 'To Dos',
            },
        ),
        migrations.AlterModelOptions(
            name='sample_data',
            options={'verbose_name_plural': 'Sample Data'},
        ),
        migrations.AlterField(
            model_name='sample_data',
            name='family',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='family'),
        ),
        migrations.AlterField(
            model_name='sample_data',
            name='genus',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='genus'),
        ),
        migrations.AlterField(
            model_name='sample_data',
            name='klass',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='sample_data',
            name='order',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='sample_data',
            name='phylum',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='phylum'),
        ),
    ]
