# Generated by Django 3.2.12 on 2022-03-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugbase', '0005_auto_20220324_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(null=True, verbose_name='Start Time')),
                ('stop', models.DateTimeField(null=True, verbose_name='Stop Time')),
                ('task', models.CharField(blank=True, max_length=256, null=True, verbose_name='Task')),
                ('bill_to', models.CharField(blank=True, max_length=32, null=True, verbose_name='Task')),
                ('billed', models.BooleanField(default=False, verbose_name='Billed')),
            ],
            options={
                'verbose_name_plural': 'Time Log',
            },
        ),
        migrations.AlterModelOptions(
            name='to_do',
            options={'verbose_name_plural': 'To Do'},
        ),
    ]
